name = "macos-work"

packages = [
  "aerospace",
  "bat",
  "bottom",
  "choose",
  "codebook",
  "delta",
  "deno",
  "direnv",
  "eza",
  "fd",
  "fish",
  "font-cascadia-code-nf",
  "fzf",
  "ghostty",
  "git",
  "go",
  "gopls",
  "glow", # for yazi preview
  "helix",
  "just",
  "just-lsp",
  "lazydocker",
  "lazygit",
  "marksman",
  "nix",
  "nushell",
  "ouch",
  "uv",
  "semble",
  "orbstack",
  "ripgrep",
  "sd",
  "swiftbar",
  "vscode-json-languageserver",
  "yaml-language-server",
  "yazi",
  "zoxide",
]

[[managers]]
name = "nix"
priority = 100

[[managers]]
name = "brew"
priority = 20

[[managers]]
name = "brew-cask"
priority = 20

[[managers]]
name = "github"
priority = 10

[[managers]]
name = "uv"
priority = 10
