format = """
┌ $hostname$git_branch$git_status$memory_usage$env_var$custom
└ $jobs$status$character$directory\
 """

command_timeout = 2000

[git_status]
format = '([\[$deleted$modified$staged$untracked\]]($style) )'
untracked = '($count)?'
modified = '($count)!'
staged = '($count)+'
deleted = '($count)✘'

[directory]
style = "bold"

[hostname]
ssh_only = false
format = '[α \($hostname\)]($style) '
style = "bold yellow"

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
