name = "codex"
tags = ["ai", "tui"]

[[managers]]
name = 'github'
repo = 'openai/codex'
version = 'rust-v0.147.0'

[managers.dist]
filename_contains = 'codex-x86_64-unknown-linux-musl.tar.gz'

[[managers.dist.files]]
source = 'codex-x86_64-unknown-linux-musl'
dest = 'bin/codex'
