name = 'rclone'
tags = ['backup']

[[managers]]
name = 'github'
repo = 'rclone/rclone'
version = 'v1.74.3'

[managers.dist]
filename_contains = 'linux-amd64.zip'

[[managers.dist.files]]
source = 'rclone'
dest = 'bin/'
