[mgr]
sort_by        = "natural"
sort_dir_first = true
show_hidden    = true
show_symlink   = true
scrolloff      = 5
linemod        = "size"
ratio          = [1, 2, 5]

[preview]
tab_size      = 2
max_width     = 1920
max_height    = 1080
image_filter  = "lanczos3"
image_quality = 80

[tasks]
suppress_preload = true

[[plugin.prepend_previewers]]
url = "*.csv"
run  = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
url = "*.json"
run  = 'piper -- nu --stdin -c "open $1"'

[[plugin.prepend_previewers]]
url = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.preprend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run = "piper -- ouch list"

[[plugin.prepend_previewers]]
url = "*/"
run  = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'

[[plugin.prepend_fetchers]]
id   = "git"
url = "*"
run  = "git"
group = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*/"
run  = "git"
group = "git"
