[language-server.phpactor]
command = "phpactor"
args = [ "language-server" ]

[[language]]
name = "php"
file-types = ["php"]
indent = { tab-width = 2, unit = " " }
language-servers = [ "phpactor" ]
formatter = { command = "sd", args = ["[\\ \\t]*$", ""] }
auto-format = true
