[language-server.phpactor]
command = "phpactor"
args = [ "language-server" ]

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "markdown"
language-servers = ["codebook", "marksman"]

[[language]]
name = "go"
auto-format = true

[[language]]
name = "php"
file-types = ["php"]
indent = { tab-width = 2, unit = " " }
language-servers = [ "phpactor" ]
formatter = { command = "sd", args = ["[\\ \\t]*$", ""] }
auto-format = true

[[language]]
name = "tl"
file-types = ["tl"]
scope = "source.tl"
comment-tokens = "//"

[[grammar]]
name = "tl"
source = { git = "https://github.com/pstripe/tree-sitter-tl", rev = "main" }
