dictionaries = [
    "en_gb",
    "en_us",
    "ru",
]
words = [
    "chmod",
    "customisations",
    "gitlab",
    "traefik",
    "БД",
    "ЕКП",
    "акторы",
    "баги",
    "бюджетирования",
    "валидации",
    "валидировать",
    "валидируется",
    "валидируются",
    "веба",
    "вебе",
    "выкатка",
    "выкатки",
    "дашборд",
    "деплой",
    "деплоймента",
    "деплою",
    "деплоя",
    "инициализируются",
    "кеширование",
    "кешировании",
    "кешировать",
    "конфдаты",
    "конфиг",
    "конфига",
    "конфигами",
    "конфиги",
    "конфигов",
    "конфигурировать",
    "линтера",
    "логирования",
    "маппинг",
    "медиа",
    "мессенджер",
    "мессенджера",
    "микросервис",
    "невалидны",
    "оркестрирующий",
    "пайплайна",
    "пайплайне",
    "паттерн",
    "паттерна",
    "пересобирает",
    "проксирующий",
    "репозитории",
    "репозиторий",
    "репозитория",
    "роутер",
    "сервисам",
    "сервисами",
    "сервисах",
    "сервисов",
    "сервисы",
    "сериализации",
    "склонировать",
    "скриншот",
    "сущностями",
    "таймаутами",
    "таймауты",
    "тогглами",
    "токен",
    "токена",
    "токенов",
    "токеном",
    "токены",
    "форматтеры",
    "фреймворк",
    "чатов",
    "чаты",
    "юзера",
]
